TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'M12.Foundation': TRUE

#    userInterface:
#      requireJsPathMapping:
#        'M12.Foundation/Inspector/Editors': 'resource://M12.Foundation/Public/JavaScript/Neos/Inspector/Editors'

    nodeTypes:
      groups:
        interactive:
          label: 'Interactive'
        forms:
          label: 'Form elements'
        navigation:
          label: 'Navigation'

M12:
  Foundation:
    gridSize: 12

    devices:
      small:
        label: 'Small device'
      medium:
        label: 'Medium device'
      large:
        label: 'Large device'
      xlarge:
        label: 'X-Large device'

    gridRowSettings:
      classCollapse:
        label: 'Collapse: remove column gutters (pading)'
        cssClassSuffixes: [ '-collapse', '-uncollapse' ] # e.g. small-text-left
        appliedPerColumn: false
        uiInspectorGroup: gridOptions
        extraValues:
          start:
            'collapse':
              label: 'all devices: collapse'
              group: All devices
          end: [ ]

    # @see AbstractGridNodeTypePostprocessor which utilizes these settings
    # to generate required properties for M12.Foundation:GridColumn node type
    gridColumnSettings:
      size:
        label: 'Grid column width'
        cssClassSuffixes: [ '-' ]         # DEVICE-X, eg: small-X, medium-Y, large-Z
        appliedPerColumn: true
        uiInspectorGroup: grid
      offset:
        label: 'Grid column offset'
        cssClassSuffixes: [ '-offset-' ]  # DEVICE-offset-X, eg: small-offset-X, medium-offset-Y, large-offset-Z
        appliedPerColumn: true
        uiInspectorGroup: grid
      pushPull:
        label: 'Grid column push / pull'
        cssClassSuffixes: [ '-push-', '-pull-' ]    # DEVICE-push-X, eg: small-push-X, medium-push-Y, large-push-Z
        appliedPerColumn: true
        uiInspectorGroup: grid
      align:
        label: 'Grid column align'
        cssClassSuffixes: [ '-centered', '-uncentered' ] # e.g. small-centered, large-centered
        appliedPerColumn: false
        uiInspectorGroup: grid
      resetOrder:
        label: 'Grid column reset order'
        cssClassSuffixes: [ '-reset-order' ]  # e.g. small-reset-order
        appliedPerColumn: false
        uiInspectorGroup: grid

    # @see AbstractGridNodeTypePostprocessor which utilizes these settings
    # to generate required properties for M12.Foundation:BlockGrid node type
    blockGridSettings:
      itemsPerRow:
        label: 'Number of items per row'
        cssClassSuffixes: [ '-block-grid-' ]    # DEVICE-block-grid-X, eg: small-block-grid-X, medium-block-grid-Y, large-block-grid-Z
        appliedPerColumn: true
        uiInspectorGroup: grid
        defaults: # default values per-device
          - small-block-grid-1
          - medium-block-grid-2
          - large-block-grid-3

    genericHelpers:
      classTextAlign:
        label: 'Text align'
        cssClassSuffixes: [ '-text-left', '-text-center', '-text-right', '-text-justify' ] # e.g. small-text-left
        appliedPerColumn: false
        uiInspectorGroup: utilityClasses
        uiInspectorPosition: 25
        extraValues:
          start:
            'text-left':
              label: 'all devices: left'
              group: All devices
            'text-center':
              label: 'all deviecs: center'
              group: All devices
            'text-right':
              label: 'all devices: right'
              group: All devices
            'text-justify':
              label: 'all devices: justify'
              group: All devices
          end: [ ]
